services:
  - type: web
    name: abz-agency
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: APP_URL
        fromService:
          type: web
          name: abz-agency
          property: host
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: abz-agency-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: abz-agency-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: abz-agency-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: abz-agency-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: abz-agency-db
          property: password
      - key: TINYPNG_API_KEY
        sync: false

databases:
  - name: abz-agency-db
    plan: free
